---
- name: copy over sql script for postgresql to run
  copy: src={{ DATABASE_FILE_TO_BE_LOADED }} dest={{ POSTGRES_SQL_INSTALL_DIRECTORY }}

- name: run sql script for postgresql
  become: yes
  become_user: postgres
  command: psql -d {{ DBNAME }} -f {{ TARGET_SQL_LOAD_FILE }}
  register: output

- debug: var=output.stdout_lines
  when: CLANK_VERBOSE | default(False)
