---
- name: Checking for necessary --extra_vars
  hosts: all
  tasks:
    - fail:
        msg: "Variable `database_names` is required, try -e \"{database_names: ['atmo_prod', 'troposphere']}\""
      when: database_names is undefined or database_names == []

- name: Ensure PostgreSQL service available
  hosts: all

  tasks:
    - service: name=postgresql state=started

- name: Backup all Postgres tables
  hosts: all

  roles:
    - { role: app-backup-postgres,
        tags: ['data-backup', 'backup', 'upgrade'] }

